name: Build

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Gradle build
        run: ./gradlew build -s -i

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: choose-browser.apk
          path: app/build/outputs/apk/release/*.apk
